Update update_db add drop_tables & drop_connections
Eliminate need to drop whole cuny_curriculum db each time.

diff --git a/update_db b/update_db
--- a/update_db
+++ b/update_db
@@ -104,23 +104,24 @@ function send_notice () {
   # Command line option processing
   export progress=''
   export report=''
+  unset progress report no_events skip_download no_size_check no_date_check no_archive no_programs
   while [ $# -gt 0 ]
   do
     if [[ ( "$1" == "--interactive" ) || ( "$1" == '-i' ) ]]
     then progress='--progress'
          report='--report'
     elif [[ ( "$1" == "--no-events" ) || ( "$1" == "-ne" ) ]]
-    then no_events=1
+    then no_events=true
     elif [[ ( "$1" == "--skip-download") || ( "$1" == "-sd" ) ]]
-      then skip_download=1
+      then skip_download=true
     elif [[ ( "$1" == "--no-size-check") || ( "$1" == "-ns" ) ]]
-      then no_size_check=1
+      then no_size_check=true
     elif [[ ( "$1" == "--no-date-check") || ( "$1" == "-nd" ) ]]
-      then no_date_check=1
+      then no_date_check=true
     elif [[ ( "$1" == "--no-archive") || ( "$1" == "-na" ) ]]
-      then no_archive=1
+      then no_archive=true
     elif [[ ( "$1" == "--no-programs" ) || ( "$1" == "-np" ) ]]
-      then no_programs=1
+      then no_programs=true
     else
       echo "Usage: $0 [-ne | --no-events] [-ns | --no-size-check] [-nd | --no-date-check]
        [-na | --no-archive] [-sd | --skip_download] [-np | --no_programs] [-i | --interactive]"
@@ -143,15 +144,15 @@ truncate -s0 update*.log
   SECONDS=0
   send_notice "Started updating database cuny_curriculum on $HOSTNAME"
 
-  # Archive non-CUNYfirst tables
-  echo "Archive registered program and requirements tables" | tee -a ./update.log
-  (
-   cd /Users/vickery/CUNY_Programs
-   ./archive_tables.sh
-  ) | tee -a ./update.log
+  # # Archive non-CUNYfirst tables
+  # echo "Archive registered programs and requirements tables" | tee -a ./update.log
+  # (
+  #  cd /Users/vickery/CUNY_Programs
+  #  ./archive_tables.sh
+  # ) | tee -a ./update.log
 
   # Try downloading new queries
-  if [[ $skip_download == 1 ]]
+  if [[ $skip_download ]]
   then echo "SKIPPING DOWNLOADS." | tee -a update.log
   else
     echo -n "DOWNLOAD new query files... " | tee -a update.log
@@ -180,51 +181,54 @@ truncate -s0 update*.log
   # Enter update_db mode and give time for running queries to complete
   echo "START update_db mode" | tee -a update.log
   redis-cli -h localhost set update_db_started `date +%s`
-  echo -n "WAIT for any running queries to complete ... "
-  sleep 10
-  echo "done"
+  # echo -n "WAIT for any running queries to complete ... "
+  # sleep 10
+  # echo "done"
 
-  # Save events table unless suppressed by command line
-  if [[ $no_events == 1 ]]
-  then
-    echo "SKIPPING events table SAVE/RESTORE." | tee -a update.log
-  else
-    echo -n SAVE events table to $EVENTS_TABLE ... | tee -a update_psql.log
-    pg_dump --data-only --table=events -f $EVENTS_TABLE cuny_curriculum >> update_psql.log
-    if [[ $? -ne 0 ]]
-      then  redis-cli -h localhost set update_db_started 0
-            send_notice "ERROR: unable to save events_table"
-            exit 1
-    fi
-    echo done. | tee -a update_psql.log
-  fi
+  # # Save events table unless suppressed by command line
+  # if [[ $no_events == 1 ]]
+  # then
+  #   echo "SKIPPING events table SAVE/RESTORE." | tee -a update.log
+  # else
+  #   echo -n SAVE events table to $EVENTS_TABLE ... | tee -a update_psql.log
+  #   pg_dump --data-only --table=events -f $EVENTS_TABLE cuny_curriculum >> update_psql.log
+  #   if [[ $? -ne 0 ]]
+  #     then  redis-cli -h localhost set update_db_started 0
+  #           send_notice "ERROR: unable to save events_table"
+  #           exit 1
+  #   fi
+  #   echo done. | tee -a update_psql.log
+  # fi
 
   # Kill any existing connections to the db
-  echo -n "RESTART postgres ... " | tee -a update_psql.log
-  brew services restart postgresql >> update_psql.log
-  echo -n "wait for postgres restart to complete... " | tee -a update_psql.log
-  sleep 10
-  echo done. | tee -a update_psql.log
-  # Do the drop
-  echo -n "DROP cuny_curriculum... " | tee -a update_psql.log
-  dropdb cuny_curriculum >> update_psql.log
-  if [[ $? -ne 0 ]]
-    then  redis-cli -h localhost set update_db_started 0
-          send_notice 'ERROR: failed to drop cuny_curriculum db'
-          exit 1
-  fi
+  echo -n "DROP Connections and Tables ... " | tee -a update_psql.log
+  psql -X -q -d cuny_curriculum -f drop_connections.sql >> update_psql.log
+  psql -X -q -d cuny_curriculum -f drop_tables.sql >> update_psql.log
 
-  echo -n "CREATE cuny_curriculum... " | tee -a update_psql.log
-  createdb cuny_curriculum >> update_psql.log
-  if [[ $? -ne 0 ]]
-    then send_notice 'ERROR: failed to create cuny_curriculum db'
-         exit 1
-  fi
-  echo done. | tee -a update_psql.log
+  # brew services restart postgresql >> update_psql.log
+  # echo -n "wait for postgres restart to complete... " | tee -a update_psql.log
+  # sleep 10
+  # echo done. | tee -a update_psql.log
+  # # Do the drop
+  # echo -n "DROP cuny_curriculum... " | tee -a update_psql.log
+  # dropdb cuny_curriculum >> update_psql.log
+  # if [[ $? -ne 0 ]]
+  #   then  redis-cli -h localhost set update_db_started 0
+  #         send_notice 'ERROR: failed to drop cuny_curriculum db'
+  #         exit 1
+  # fi
 
-  echo -n "CREATE TABLE updates... " | tee -a update_psql.log
-  psql -X -q -d cuny_curriculum -f updates.sql >> update_psql.log
-  echo done. | tee -a update_psql.log
+  # echo -n "CREATE cuny_curriculum... " | tee -a update_psql.log
+  # createdb cuny_curriculum >> update_psql.log
+  # if [[ $? -ne 0 ]]
+  #   then send_notice 'ERROR: failed to create cuny_curriculum db'
+  #        exit 1
+  # fi
+  # echo done. | tee -a update_psql.log
+
+  # echo -n "CREATE TABLE updates... " | tee -a update_psql.log
+  # psql -X -q -d cuny_curriculum -f updates.sql >> update_psql.log
+  # echo done. | tee -a update_psql.log
 
   echo -n "CREATE FUNCTIONs numeric_part and rule_key ... " | tee -a update_psql.log
   psql -X -q -d cuny_curriculum -f numeric_part.sql >> update_psql.log
@@ -396,42 +400,42 @@ truncate -s0 update*.log
   # fi
   # echo done. | tee -a update_psql.log
 
-  #echo CREATE TABLE pending_reviews...
-  #echo CREATE TABLE event_types...
-  echo -n "CREATE TABLE events... " | tee -a update_psql.log
-  psql -X -q -d cuny_curriculum -f reviews-events.sql >> update_psql.log 2>&1
-  if [ $? -ne 0 ]
-    then send_notice 'ERROR: reviews-events failed'
-         exit 1
-  fi
-  echo done. | tee -a update_psql.log
+  # #echo CREATE TABLE pending_reviews...
+  # #echo CREATE TABLE event_types...
+  # echo -n "CREATE TABLE events... " | tee -a update_psql.log
+  # psql -X -q -d cuny_curriculum -f reviews-events.sql >> update_psql.log 2>&1
+  # if [ $? -ne 0 ]
+  #   then send_notice 'ERROR: reviews-events failed'
+  #        exit 1
+  # fi
+  # echo done. | tee -a update_psql.log
 
-  if [[ $no_events -ne 1 ]]
-  then
-    echo -n "RESTORE previous events from $EVENTS_TABLE ... " | tee -a update_psql.log
-    psql -X -q -d cuny_curriculum -f $EVENTS_TABLE >> update_psql.log 2>&1
-    if [ $? -ne 0 ]
-      then send_notice 'ERROR: restore events_table failed'
-           exit 1
-    fi
-    echo done. | tee -a update_psql.log
+  # if [[ ! $no_events ]]
+  # then
+  #   echo -n "RESTORE previous events from $EVENTS_TABLE ... " | tee -a update_psql.log
+  #   psql -X -q -d cuny_curriculum -f $EVENTS_TABLE >> update_psql.log 2>&1
+  #   if [ $? -ne 0 ]
+  #     then send_notice 'ERROR: restore events_table failed'
+  #          exit 1
+  #   fi
+  #   echo done. | tee -a update_psql.log
 
-    echo ARCHIVE the events table.
-    mv $EVENTS_TABLE ./event_dumps/
+  #   echo ARCHIVE the events table.
+  #   mv $EVENTS_TABLE ./event_dumps/
 
-    echo -n "UPDATE review statuses... " | tee -a update.log
-    python3 update_review_statuses.py >> update.log 2>&1
-    if [ $? -ne 0 ]
-      then send_notice 'ERROR: review_statuses failed'
-           exit 1
-    fi
-    echo done. | tee -a update.log
-  fi
+  #   echo -n "UPDATE review statuses... " | tee -a update.log
+  #   python3 update_review_statuses.py >> update.log 2>&1
+  #   if [ $? -ne 0 ]
+  #     then send_notice 'ERROR: review_statuses failed'
+  #          exit 1
+  #   fi
+  #   echo done. | tee -a update.log
+  # fi
 
-  # User roles and access
-  echo -n "Re-build the roles and person_roles tables ..." | tee -a update_psql.log
-  psql -X -q -d cuny_curriculum -f roles.sql >> update_psql.log 2>&1
-  echo done. | tee -a update_psql.log
+  # # User roles and access
+  # echo -n "Re-build the roles and person_roles tables ..." | tee -a update_psql.log
+  # psql -X -q -d cuny_curriculum -f roles.sql >> update_psql.log 2>&1
+  # echo done. | tee -a update_psql.log
 
   echo -n "(Re-)Grant select access to view_only ROLE ..." | tee -a update_psql.log
   psql -X -q -d cuny_curriculum -f view_only_role.sql >> update_psql.log 2>&1
@@ -439,7 +443,7 @@ truncate -s0 update*.log
   echo done. | tee -a update_psql.log
 
 
-if [[ ! ( $no_programs == 1 || $no_programs == true ) ]]
+if [[ ! $no_programs ]]
 then
   echo "And now for CUNY_Programs ... " | tee -a update.log
   (
@@ -465,5 +469,6 @@ fi
   # Exit update_db mode
   echo -n "END update_db mode: " | tee -a update.log
   redis-cli -h localhost set update_db_started 0
+  ~/Transfer_App/start
   echo done. | tee -a update.log
 )
