Tweak update logs.

diff --git a/update_db b/update_db
--- a/update_db
+++ b/update_db
@@ -17,6 +17,7 @@
 
 (
   export PGOPTIONS='--client-min-messages=warning'
+  export EVENTS_TABLE=events-dump_`date +'%F_%H:%M'`.sql
 
   # CHECK COMMAND LINE
   # Default is to dump and restore events. But -n or --no-events suppresses it.
@@ -45,32 +46,30 @@
   fi
 
   # Enter update_db mode
-  echo -n "START_UPDATE ..." | tee -a init.log
+  echo "START update_db mode" | tee -a init.log
   psql access_control -c \
         "update access_control set start_time = now() where event_type = 'update_db'"
 
   # Save events table unless suppressed by command line
   if [ $do_events -eq 1 ]
   then
-    # If the db has no events table (yet), re-use the existing events-dump.sql if there is one, or
-    # create an empty one.
-    touch events-dump.sql
-    echo -n SAVE EVENTS TABLE ...
-    # events-dump.sql won’t be changed if "no matching tables found"
-    pg_dump --data-only --table=events -f events-dump_`date +'%F_%H:%M'`.sql cuny_courses
-    # Convert old-style group numbers (ints) to floats
-    #   This can go away once all old-style reviews have been converted.
-    # python3 fix_events_dump.py < events-dump_`date -I`.sql > t.sql
-    # mv t.sql events-dump.sql
-    echo done.
+    echo -n SAVE events table to $EVENTS_TABLE ... | tee init_psql.log
+    pg_dump --data-only --table=events -f $EVENTS_TABLE cuny_courses | tee -a init_psql.log
+    if [[ $? -ne 0 ]]
+      then  echo -e '\nFAILED!'
+            psql access_control -c \
+            "update access_control set start_time = NULL where event_type = 'update_db'"
+            exit
+    fi
+    echo done. | tee -a init_psql.log
   fi
 
-  echo -n "DROP cuny_courses... " | tee init_psql.log
+  echo -n "DROP cuny_courses... " | tee -a init_psql.log
   # Kill any existing connections to the db
-  brew services restart postgresql
+  brew services restart postgresql | tee -a init_psql.log
   sleep 2
   # Do the drop
-  dropdb cuny_courses >> init_psql.log
+  dropdb cuny_courses >> init_psql.log | tee -a init_psql.log
   if [[ $? -ne 0 ]]
     then  echo -e '\nFAILED!'
           psql access_control -c \
@@ -171,7 +170,7 @@
     then echo -e '\nFAILED!'
          exit
   fi
-  echo done. | tee -a init.log
+  echo done. | tee -a init_psql.log
 
   echo -n "POPULATE courses... " | tee -a init.log
   python3 populate_courses.py --progress >> init.log
@@ -196,16 +195,16 @@
     then echo -e '\nFAILED!'
          exit
   fi
-  echo done. | tee -a init.log
+  echo done. | tee -a init_psql.log
 
-  echo -n "CREATE TABLEs transfer_rules source_courses destination_courses... " | tee -a init_psql.log
+  echo -n "CREATE transfer_rules, source_courses, destination_courses... " | tee -a init_psql.log
   psql -X -q -d cuny_courses -f create_transfer_rules.sql >> init_psql.log
   psql -X -q -d cuny_courses -f view_transfer_rules.sql >> init_psql.log
   if [ $? -ne 0 ]
     then echo -e '\nFAILED!'
          exit
   fi
-  echo done. | tee -a init.log
+  echo done. | tee -a init_psql.log
 
   echo -n "POPULATE transfer_rules... " | tee -a init.log
   python3 populate_transfer_rules.py --progress --report >> init.log
@@ -241,7 +240,7 @@
     then echo -e '\nFAILED!'
          exit
   fi
-  echo done. | tee -a init.log
+  echo done. | tee -a init_psql.log
 
   #echo CREATE TABLE pending_reviews...
   #echo CREATE TABLE event_types...
@@ -251,17 +250,17 @@
     then echo -e '\nFAILED!'
          exit
   fi
-  echo done. | tee -a init.log
+  echo done. | tee -a init_psql.log
 
   if [ $do_events -eq 1 ]
   then
-    echo -n "RESTORE previous events... " | tee -a init_psql.log
-    psql -X -q -d cuny_courses -f events-dump.sql >> init_psql.log
+    echo -n "RESTORE previous events from $EVENTS_TABLE ... " | tee -a init_psql.log
+    psql -X -q -d cuny_courses -f $EVENTS_TABLE >> init_psql.log
     if [ $? -ne 0 ]
       then echo -e '\nFAILED!'
            exit
     fi
-    echo done. | tee -a init.log
+    echo done. | tee -a init_psql.log
 
     echo -n "UPDATE review statuses... " | tee -a init.log
     python3 update_review_statuses.py >> init.log
@@ -272,15 +271,10 @@
     echo done. | tee -a init.log
   fi
 
-  # Exit update_db mode if local server is running
-  ps -fe | ack '[g]unicorn|main.py' > /dev/null
-  if [[ $? == 0 ]]
-  then
-        psql access_control -c \
+  # Exit update_db mode
+  echo "END update_db mode" | tee -a init.log
+  psql  access_control -c \
         "update access_control set start_time = NULL where event_type = 'update_db'"
-
-  fi
-
 
   echo UPDATE COMPLETED in `date -d @"$SECONDS" +'%-Mm %-Ss'` | tee -a init.log
 )
