Update update_db and populate {courses|rules}
Cleaning up progress reporting for interactive mode.
## To make a commit, type your commit message and press SUPER-ENTER. To cancel
## the commit, close the window. To sign off on the commit, press SUPER-S.
##
## You may also reference or close a GitHub issue with this commit.  To do so,
## type `#` followed by the `tab` key.  You will be shown a list of issues
## related to the current repo.  You may also type `owner/repo#` plus the `tab`
## key to reference an issue in a different GitHub repo.

 populate_courses.py        |  9 +++--
 populate_transfer_rules.py | 21 ++++++-----
 update_db                  | 87 ++++++++++++++++++++++++----------------------
 3 files changed, 59 insertions(+), 58 deletions(-)

diff --git a/update_db b/update_db
--- a/update_db
+++ b/update_db
@@ -9,26 +9,21 @@
 
 export WEBMASTER='<Christopher Vickery> christopher.vickery@qc.cuny.edu'
 
-function update_failure () {
+function send_notice () {
 
-  rm -f ./failure_report
+  rm -f ./notification_report
   for file in update*.log
   do
-    echo -e "\n--- $file ---" >> ./failure_report
-    cat $file >> failure_report
+    echo -e "\n--- $file ---" >> ./notification_report
+    cat $file >> notification_report
   done
 
   # sendemail must be in the PATH as a (hard) link to sendemail.py in transfer-app.
-  sendemail -s "Update_db failed! $1" -t ./failure_report "$WEBMASTER"
+  sendemail -s "Update_db Notice $1" -t ./notification_report "$WEBMASTER"
 
-  rm -f failure_report
+  rm -f notification_report
   echo "$1. Notice sent to $WEBMASTER."
-  exit 1
 }
-
-###################################################################################################
-#  TODO: modify the rest of this script to use the update_failure function for error management.  #
-###################################################################################################
 
 # Summary of recommendations for running psql from a script, taken from:
 #    http://petereisentraut.blogspot.com/2010/03/running-sql-scripts-with-psql.html
@@ -101,9 +96,14 @@ function update_failure () {
   done
 
   # Command line option processing
+  export progress=''
+  export report=''
   while [ $# -gt 0 ]
   do
-    if [[ ( "$1" == "--no-events" ) || ( "$1" == "-ne" ) ]]
+    if [[ ( "$1" == "--interactive" ) || ( "$1" == '-i' ) ]]
+    then progress='--progress'
+         report='--report'
+    elif [[ ( "$1" == "--no-events" ) || ( "$1" == "-ne" ) ]]
     then no_events=1
     elif [[ ( "$1" == "--skip-download") || ( "$1" == "-sd" ) ]]
       then skip_download=1
@@ -117,7 +117,7 @@ function update_failure () {
       then no_programs=1
     else
       echo "Usage: $0 [-ne | --no-events] [-ns | --no-size-check] [-nd | --no-date-check]
-       [-na | --no-archive] [-sd | --skip_download] [-np | --no_programs]"
+       [-na | --no-archive] [-sd | --skip_download] [-np | --no_programs] [-i | --interactive]"
       exit 1
     fi
     shift
@@ -135,6 +135,7 @@ function update_failure () {
 truncate -s0 update*.log
   echo BEGIN UPDATE at `date +"%Y-%m-%d %T"` | tee -a ./update.log
   SECONDS=0
+  send_notice 'Started updating database cuny_courses'
 
   # Try downloading new queries
   if [[ $skip_download == 1 ]]
@@ -158,7 +159,7 @@ truncate -s0 update*.log
   [[ $no_archive == 1 ]] && args="$args -sa"
   ./check_queries.py $args >> update.log 2>&1
   if [ $? -ne 0 ]
-    then update_failure "ERROR: query checks failed"
+    then send_notice "ERROR: query checks failed"
          exit 1
     else echo "done." | tee -a update.log
   fi
@@ -179,7 +180,7 @@ truncate -s0 update*.log
     if [[ $? -ne 0 ]]
       then  psql access_control -c \
             "update access_control set start_time = NULL where event_type = 'update_db'"
-            update_failure "ERROR: unable to save events_table"
+            send_notice "ERROR: unable to save events_table"
             exit 1
     fi
     echo done. | tee -a update_psql.log
@@ -197,7 +198,7 @@ truncate -s0 update*.log
   if [[ $? -ne 0 ]]
     then  psql access_control -c \
           "update access_control set start_time = NULL where event_type = 'update_db'"
-          update_failure 'ERROR: failed to drop cuny_courses db'
+          send_notice 'ERROR: failed to drop cuny_courses db'
           exit 1
 
   fi
@@ -205,7 +206,7 @@ truncate -s0 update*.log
   echo -n "CREATE cuny_courses... " | tee -a update_psql.log
   createdb cuny_courses >> update_psql.log
   if [[ $? -ne 0 ]]
-    then update_failure 'ERROR: failed to create cuny_courses db'
+    then send_notice 'ERROR: failed to create cuny_courses db'
          exit 1
   fi
   echo done. | tee -a update_psql.log
@@ -239,7 +240,7 @@ truncate -s0 update*.log
   echo -n "CREATE academic_programs... " | tee -a update_psql.log
   python3 populate_programs.py >> update.log 2>&1
   if [[ $? -ne 0 ]]
-    then update_failure 'ERROR: populate_programs failed'
+    then send_notice 'ERROR: populate_programs failed'
          exit 1
   fi
   echo done. | tee -a update_psql.log
@@ -249,7 +250,7 @@ truncate -s0 update*.log
   echo -n "CREATE TABLE cuny_careers... " | tee -a update.log
   python3 cuny_careers.py >> update.log 2>&1
   if [ $? -ne 0 ]
-    then update_failure 'ERROR: cuny_careers failed'
+    then send_notice 'ERROR: cuny_careers failed'
          exit 1
   fi
   echo done. | tee -a update.log
@@ -257,7 +258,7 @@ truncate -s0 update*.log
   echo -n "CREATE TABLE cuny_departments... " | tee -a update.log
   python3 cuny_departments.py >> update.log 2>&1
   if [ $? -ne 0 ]
-    then update_failure 'ERROR: cuny_departments failed'
+    then send_notice 'ERROR: cuny_departments failed'
          exit 1
   fi
   echo done. | tee -a update.log
@@ -265,7 +266,7 @@ truncate -s0 update*.log
   echo -n "CREATE TABLE cuny_divisions... " | tee -a update.log
   python3 cuny_divisions.py --active_only >> update.log 2>&1
   if [ $? -ne 0 ]
-    then update_failure 'ERROR: cuny_divisions failed'
+    then send_notice 'ERROR: cuny_divisions failed'
          exit 1
   fi
   echo done. | tee -a update.log
@@ -273,7 +274,7 @@ truncate -s0 update*.log
   echo -n "CREATE TABLE cuny_subjects... " | tee -a update.log
   python3 cuny_subjects.py >> update.log 2>&1
   if [ $? -ne 0 ]
-    then update_failure 'ERROR: cuny_subjects failed'
+    then send_notice 'ERROR: cuny_subjects failed'
          exit 1
   fi
   echo done. | tee -a update.log
@@ -281,7 +282,7 @@ truncate -s0 update*.log
   echo -n "CREATE TABLE designations... " | tee -a update.log
   python3 designations.py >> update.log 2>&1
   if [ $? -ne 0 ]
-    then update_failure 'ERROR: designations failed'
+    then send_notice 'ERROR: designations failed'
          exit 1
   fi
   echo done. | tee -a update.log
@@ -289,27 +290,28 @@ truncate -s0 update*.log
   echo -n "CREATE TABLE crse_quiv_tbl... " | tee -a update.log
   python3 mk_crse_equiv_tbl.py >> update.log 2>&1
   if [ $? -ne 0 ]
-    then update_failure 'ERROR: mk_crse_equiv_tbl failed'
+    then send_notice 'ERROR: mk_crse_equiv_tbl failed'
          exit 1
   fi
   echo done. | tee -a update.log
 
-  echo -n "CREATE TABLE courses... " | tee -a update_psql.log
+  echo -n "CREATE TABLE courses... " | tee -a update.log
   psql -X -q -d cuny_courses -f create_courses.sql >> update_psql.log 2>&1
   if [ $? -ne 0 ]
-    then update_failure 'ERROR: create_courses failed'
+    then send_notice 'ERROR: create_courses failed'
+         exit 1
   fi
   psql -X -q -d cuny_courses -f view_courses.sql >> update_psql.log 2>&1
   if [ $? -ne 0 ]
-    then update_failure 'ERROR: view_courses failed'
+    then send_notice 'ERROR: view_courses failed'
          exit 1
   fi
   echo done. | tee -a update_psql.log
 
   echo -n "POPULATE courses... " | tee -a update.log
-  python3 populate_courses.py --progress >> update.log 2>&1
+  python3 populate_courses.py $progress >> update.log 2>&1
   if [ $? -ne 0 ]
-    then update_failure 'ERROR: populate_courses failed'
+    then send_notice 'ERROR: populate_courses failed'
          exit 1
   fi
   echo done. | tee -a update.log
@@ -317,7 +319,7 @@ truncate -s0 update*.log
   echo -n "CHECK component contact hours... " | tee -a update.log
   python3 check_total_hours.py > check_contact_hours.log 2>&1
   if [ $? -ne 0 ]
-    then update_failure 'ERROR: check_total_hours failed'
+    then send_notice 'ERROR: check_total_hours failed'
          exit 1
   fi
   echo done. | tee -a update.log
@@ -326,7 +328,7 @@ truncate -s0 update*.log
   echo -n "CREATE TABLE review_status_bits... " | tee -a update_psql.log
   psql -X -q -d cuny_courses -f review_status_bits.sql >> update_psql.log 2>&1
   if [ $? -ne 0 ]
-    then update_failure 'ERROR: review_status_bits failed'
+    then send_notice 'ERROR: review_status_bits failed'
          exit 1
   fi
   echo done. | tee -a update_psql.log
@@ -335,23 +337,23 @@ truncate -s0 update*.log
   psql -X -q -d cuny_courses -f create_transfer_rules.sql >> update_psql.log 2>&1
   psql -X -q -d cuny_courses -f view_transfer_rules.sql >> update_psql.log 2>&1
   if [ $? -ne 0 ]
-    then update_failure 'ERROR: create/view transfer_rules failed'
+    then send_notice 'ERROR: create/view transfer_rules failed'
          exit 1
   fi
   echo done. | tee -a update_psql.log
 
   echo -n "POPULATE transfer_rules... " | tee -a update.log
-  python3 populate_transfer_rules.py --progress --report >> update.log 2>&1
+  python3 populate_transfer_rules.py $progress $report >> update.log 2>&1
   if [ $? -ne 0 ]
-    then update_failure 'ERROR: populate_transfer_rules failed'
+    then send_notice 'ERROR: populate_transfer_rules failed'
          exit 1
   fi
   echo done. | tee -a update.log
 
   echo -n "SPEEDUP transfer_rule lookups... " | tee -a update.log
-  python3 mk_subject-rule_map.py --progress >> update.log 2>&1
+  python3 mk_subject-rule_map.py $progress >> update.log 2>&1
   if [ $? -ne 0 ]
-    then update_failure 'ERROR: mk_subject-rule_map failed'
+    then send_notice 'ERROR: mk_subject-rule_map failed'
          exit 1
   fi
   echo done. | tee -a update.log
@@ -360,9 +362,9 @@ truncate -s0 update*.log
   # The following takes too long, and doesn't really do more than
   # populate_transfer_rules.py already did. Historical Artifact.
   # echo -n "CHECK bogus rules... " | tee -a update.log
-  # python3 bogus_rules.py --progress >> update.log 2>&1
+  # python3 bogus_rules.py $progress >> update.log 2>&1
   # if [ $? -ne 0 ]
-  #   then update_failure 'ERROR: bogus_rules failed'
+  #   then send_notice 'ERROR: bogus_rules failed'
   # fi
   # echo done.
 
@@ -370,7 +372,7 @@ truncate -s0 update*.log
   echo -n "CREATE TABLE sessions... " | tee -a update_psql.log
   psql -X -q -d cuny_courses -f sessions.sql >> update_psql.log 2>&1
   if [ $? -ne 0 ]
-    then update_failure 'ERROR: sessions failed'
+    then send_notice 'ERROR: sessions failed'
          exit 1
   fi
   echo done. | tee -a update_psql.log
@@ -380,7 +382,7 @@ truncate -s0 update*.log
   echo -n "CREATE TABLE events... " | tee -a update_psql.log
   psql -X -q -d cuny_courses -f reviews-events.sql >> update_psql.log 2>&1
   if [ $? -ne 0 ]
-    then update_failure 'ERROR: reviews-events failed'
+    then send_notice 'ERROR: reviews-events failed'
          exit 1
   fi
   echo done. | tee -a update_psql.log
@@ -390,7 +392,7 @@ truncate -s0 update*.log
     echo -n "RESTORE previous events from $EVENTS_TABLE ... " | tee -a update_psql.log
     psql -X -q -d cuny_courses -f $EVENTS_TABLE >> update_psql.log 2>&1
     if [ $? -ne 0 ]
-      then update_failure 'ERROR: restore events_table failed'
+      then send_notice 'ERROR: restore events_table failed'
            exit 1
     fi
     echo done. | tee -a update_psql.log
@@ -401,7 +403,7 @@ truncate -s0 update*.log
     echo -n "UPDATE review statuses... " | tee -a update.log
     python3 update_review_statuses.py >> update.log 2>&1
     if [ $? -ne 0 ]
-      then update_failure 'ERROR: review_statuses failed'
+      then send_notice 'ERROR: review_statuses failed'
            exit 1
     fi
     echo done. | tee -a update.log
@@ -423,6 +425,7 @@ truncate -s0 update*.log
 
   echo UPDATE COMPLETED at `date +"%Y-%m-%d %T"` in `gdate -d @"$SECONDS" +'%-Mm %-Ss'` | \
        tee -a update.log
+       send_notice 'Finished updating database cuny_courses'
 
 if [[ ! ( $no_programs == 1 || $no_programs == true ) ]]
 then
