update update_db and check_queries.py
Get errors to terminate the update process.
Fix bugs in check_queries.py

diff --git a/update_db b/update_db
--- a/update_db
+++ b/update_db
@@ -19,9 +19,10 @@ function update_failure () {
   done
 
   # sendemail must be in the PATH as a (hard) link to sendemail.py in transfer-app.
-  sendemail -s "$1" -t ./failure_report "$WEBMASTER"
+  sendemail -s "Update_db failed! $1" -t ./failure_report "$WEBMASTER"
 
   rm -f failure_report
+  echo "$1. Notice sent to $WEBMASTER."
   exit 1
 }
 
@@ -44,7 +45,7 @@ function update_failure () {
 
 (
   export PGOPTIONS='--client-min-messages=warning'
-  export EVENTS_TABLE=events-dump_`date +'%F_%H:%M'`.sql
+  export EVENTS_TABLE=events-dump_`gdate +'%F_%H:%M'`.sql
 
   # COMMAND LINE ARGUMENTS AND ENVIRONMENT VARIABLES
   # The update_db command normally runs with no arguments, but the normal process can be modified
@@ -108,7 +109,7 @@ function update_failure () {
       then skip_download=1
     elif [[ ( "$1" == "--no-size-check") || ( "$1" == "-ns" ) ]]
       then no_size_check=1
-    elif [[ ( "$1" == "--no-size-check") || ( "$1" == "-ns" ) ]]
+    elif [[ ( "$1" == "--no-date-check") || ( "$1" == "-nd" ) ]]
       then no_date_check=1
     elif [[ ( "$1" == "--no-archive") || ( "$1" == "-na" ) ]]
       then no_archive=1
@@ -131,14 +132,15 @@ function update_failure () {
   #   fi
   # done
 
-  echo BEGIN INITIALIZATION
+truncate -s0 update*.log
+  echo BEGIN UPDATE at `date +"%Y-%m-%d %T"` | tee -a ./update.log
   SECONDS=0
 
   # Try downloading new queries
   if [[ $skip_download == 1 ]]
   then echo "SKIPPING DOWNLOADS." | tee -a update.log
   else
-    echo -n "DOWNLOAD new query files... " | tee update.log
+    echo -n "DOWNLOAD new query files... " | tee -a update.log
     /Users/vickery/bin/get_cuny
     if [[ $? -eq 1 ]]
     then  echo "No new query files. Use --skip-download to update anyway." | tee -a update.log
@@ -149,14 +151,14 @@ function update_failure () {
   # Python scripts process query results, so check that they are all present.
   # Report any mismatched dates, truncated or abnormally-sized queries and abort if not all a-ok
 
-  echo -n "CHECK & ARCHIVE QUERY FILES... " | tee -a update.log
+  echo "CHECK & ARCHIVE QUERY FILES... " | tee -a update.log
   args='-v'
-  [[ $no_size_check == 1 ]] && args="$args -s"
-  [[ $no_date_check == 1 ]] && args="$args -d"
-  [[ $no_archive == 1 ]] && args="$args -a"
-  ./check_queries.py $args | tee -a update.log
+  [[ $no_size_check == 1 ]] && args="$args -ss"
+  [[ $no_date_check == 1 ]] && args="$args -sd"
+  [[ $no_archive == 1 ]] && args="$args -sa"
+  ./check_queries.py $args >> update.log 2>&1
   if [ $? -ne 0 ]
-    then echo "ERROR: query checks failed." | tee -a update.log
+    then update_failure "ERROR: query checks failed"
          exit 1
     else echo "done." | tee -a update.log
   fi
@@ -172,12 +174,12 @@ function update_failure () {
   then
     echo "SKIPPING events table SAVE/RESTORE." | tee -a update.log
   else
-    echo -n SAVE events table to $EVENTS_TABLE ... | tee update_psql.log
-    pg_dump --data-only --table=events -f $EVENTS_TABLE cuny_courses | tee -a update_psql.log
+    echo -n SAVE events table to $EVENTS_TABLE ... | tee -a update_psql.log
+    pg_dump --data-only --table=events -f $EVENTS_TABLE cuny_courses >> update_psql.log
     if [[ $? -ne 0 ]]
-      then  echo -e '\nFAILED!'
-            psql access_control -c \
+      then  psql access_control -c \
             "update access_control set start_time = NULL where event_type = 'update_db'"
+            update_failure "ERROR: unable to save events_table"
             exit 1
     fi
     echo done. | tee -a update_psql.log
@@ -185,25 +187,26 @@ function update_failure () {
 
   # Kill any existing connections to the db
   echo -n "RESTART postgres ..." | tee -a update_psql.log
-  brew services restart postgresql | tee -a update_psql.log
+  brew services restart postgresql >> update_psql.log
   echo -n "wait for postgres restart to complete ..." | tee -a update_psql.log
   sleep 10
   echo done. | tee -a update_psql.log
   # Do the drop
   echo -n "DROP cuny_courses... " | tee -a update_psql.log
-  dropdb cuny_courses >> update_psql.log | tee -a update_psql.log
+  dropdb cuny_courses >> update_psql.log
   if [[ $? -ne 0 ]]
-    then  echo -e '\nFAILED!'
-          psql access_control -c \
+    then  psql access_control -c \
           "update access_control set start_time = NULL where event_type = 'update_db'"
-          exit
+          update_failure 'ERROR: failed to drop cuny_courses db'
+          exit 1
+
   fi
 
   echo -n "CREATE cuny_courses... " | tee -a update_psql.log
   createdb cuny_courses >> update_psql.log
   if [[ $? -ne 0 ]]
-    then echo -e '\nFAILED!'
-         exit
+    then update_failure 'ERROR: failed to create cuny_courses db'
+         exit 1
   fi
   echo done. | tee -a update_psql.log
 
@@ -230,127 +233,126 @@ function update_failure () {
   #   Divisions references departments, so create departments first
   #
   echo -n "CREATE TABLE institutions... " | tee -a update_psql.log
-  psql -X -q -d cuny_courses -f cuny_institutions.sql >> update_psql.log
+  psql -X -q -d cuny_courses -f cuny_institutions.sql >> update_psql.log 2>&1
   echo done. | tee -a update_psql.log
 
   echo -n "CREATE academic_programs... " | tee -a update_psql.log
-  python3 populate_programs.py >> update.log
+  python3 populate_programs.py >> update.log 2>&1
   if [[ $? -ne 0 ]]
-    then echo -e '\nFAILED!'
-         exit
+    then update_failure 'ERROR: populate_programs failed'
+         exit 1
   fi
   echo done. | tee -a update_psql.log
 
   # Now regenerate the tables that are based on query results
   #
   echo -n "CREATE TABLE cuny_careers... " | tee -a update.log
-  python3 cuny_careers.py >> update.log
+  python3 cuny_careers.py >> update.log 2>&1
   if [ $? -ne 0 ]
-    then echo -e '\nFAILED!'
-         exit
+    then update_failure 'ERROR: cuny_careers failed'
+         exit 1
   fi
   echo done. | tee -a update.log
 
   echo -n "CREATE TABLE cuny_departments... " | tee -a update.log
-  python3 cuny_departments.py >> update.log
+  python3 cuny_departments.py >> update.log 2>&1
   if [ $? -ne 0 ]
-    then echo  -e '\nFAILED!'
-         exit
+    then update_failure 'ERROR: cuny_departments failed'
+         exit 1
   fi
   echo done. | tee -a update.log
 
   echo -n "CREATE TABLE cuny_divisions... " | tee -a update.log
-  python3 cuny_divisions.py --active_only >> update.log
+  python3 cuny_divisions.py --active_only >> update.log 2>&1
   if [ $? -ne 0 ]
-    then echo  -e '\nFAILED!'
-         exit
+    then update_failure 'ERROR: cuny_divisions failed'
+         exit 1
   fi
   echo done. | tee -a update.log
 
   echo -n "CREATE TABLE cuny_subjects... " | tee -a update.log
-  python3 cuny_subjects.py >> update.log
+  python3 cuny_subjects.py >> update.log 2>&1
   if [ $? -ne 0 ]
-    then echo  -e '\nFAILED!'
-         exit
+    then update_failure 'ERROR: cuny_subjects failed'
+         exit 1
   fi
   echo done. | tee -a update.log
 
   echo -n "CREATE TABLE designations... " | tee -a update.log
-  python3 designations.py >> update.log
+  python3 designations.py >> update.log 2>&1
   if [ $? -ne 0 ]
-    then echo  -e '\nFAILED!'
-         exit
+    then update_failure 'ERROR: designations failed'
+         exit 1
   fi
   echo done. | tee -a update.log
 
   echo -n "CREATE TABLE crse_quiv_tbl... " | tee -a update.log
-  python3 mk_crse_equiv_tbl.py >> update.log
+  python3 mk_crse_equiv_tbl.py >> update.log 2>&1
   if [ $? -ne 0 ]
-    then echo -e '\nFAILED!'
-         exit
+    then update_failure 'ERROR: mk_crse_equiv_tbl failed'
+         exit 1
   fi
   echo done. | tee -a update.log
 
   echo -n "CREATE TABLE courses... " | tee -a update_psql.log
-  psql -X -q -d cuny_courses -f create_courses.sql >> update_psql.log
+  psql -X -q -d cuny_courses -f create_courses.sql >> update_psql.log 2>&1
   if [ $? -ne 0 ]
-    then echo -e '\nFAILED!'
-         exit
+    then update_failure 'ERROR: create_courses failed'
   fi
-  psql -X -q -d cuny_courses -f view_courses.sql >> update_psql.log
+  psql -X -q -d cuny_courses -f view_courses.sql >> update_psql.log 2>&1
   if [ $? -ne 0 ]
-    then echo -e '\nFAILED!'
-         exit
+    then update_failure 'ERROR: view_courses failed'
+         exit 1
   fi
   echo done. | tee -a update_psql.log
 
   echo -n "POPULATE courses... " | tee -a update.log
-  python3 populate_courses.py --progress >> update.log
+  python3 populate_courses.py --progress >> update.log 2>&1
   if [ $? -ne 0 ]
-    then echo -e '\nFAILED!'
-         exit
+    then update_failure 'ERROR: populate_courses failed'
+         exit 1
   fi
   echo done. | tee -a update.log
 
   echo -n "CHECK component contact hours... " | tee -a update.log
-  python3 check_total_hours.py > check_contact_hours.log
+  python3 check_total_hours.py > check_contact_hours.log 2>&1
   if [ $? -ne 0 ]
-    then echo -e '\nFAILED!'
-         exit
+    then update_failure 'ERROR: check_total_hours failed'
+         exit 1
   fi
   echo done. | tee -a update.log
 
   # Transfer rules
   echo -n "CREATE TABLE review_status_bits... " | tee -a update_psql.log
-  psql -X -q -d cuny_courses -f review_status_bits.sql >> update_psql.log
+  psql -X -q -d cuny_courses -f review_status_bits.sql >> update_psql.log 2>&1
   if [ $? -ne 0 ]
-    then echo -e '\nFAILED!'
-         exit
+    then update_failure 'ERROR: review_status_bits failed'
+         exit 1
   fi
   echo done. | tee -a update_psql.log
 
   echo -n "CREATE transfer_rules, source_courses, destination_courses... " | tee -a update_psql.log
-  psql -X -q -d cuny_courses -f create_transfer_rules.sql >> update_psql.log
-  psql -X -q -d cuny_courses -f view_transfer_rules.sql >> update_psql.log
+  psql -X -q -d cuny_courses -f create_transfer_rules.sql >> update_psql.log 2>&1
+  psql -X -q -d cuny_courses -f view_transfer_rules.sql >> update_psql.log 2>&1
   if [ $? -ne 0 ]
-    then echo -e '\nFAILED!'
-         exit
+    then update_failure 'ERROR: create/view transfer_rules failed'
+         exit 1
   fi
   echo done. | tee -a update_psql.log
 
   echo -n "POPULATE transfer_rules... " | tee -a update.log
-  python3 populate_transfer_rules.py --progress --report >> update.log
+  python3 populate_transfer_rules.py --progress --report >> update.log 2>&1
   if [ $? -ne 0 ]
-    then echo -e '\nFAILED!'
-         exit
+    then update_failure 'ERROR: populate_transfer_rules failed'
+         exit 1
   fi
   echo done. | tee -a update.log
 
   echo -n "SPEEDUP transfer_rule lookups... " | tee -a update.log
-  python3 mk_subject-rule_map.py --progress >> update.log
+  python3 mk_subject-rule_map.py --progress >> update.log 2>&1
   if [ $? -ne 0 ]
-    then echo -e '\nFAILED!'
-         exit
+    then update_failure 'ERROR: mk_subject-rule_map failed'
+         exit 1
   fi
   echo done. | tee -a update.log
 
@@ -358,60 +360,60 @@ function update_failure () {
   # The following takes too long, and doesn't really do more than
   # populate_transfer_rules.py already did. Historical Artifact.
   # echo -n "CHECK bogus rules... " | tee -a update.log
-  # python3 bogus_rules.py --progress >> update.log
+  # python3 bogus_rules.py --progress >> update.log 2>&1
   # if [ $? -ne 0 ]
-  #   then echo -e '\nFAILED!'
-  #        exit
+  #   then update_failure 'ERROR: bogus_rules failed'
   # fi
   # echo done.
 
   # Managing the rule review process
   echo -n "CREATE TABLE sessions... " | tee -a update_psql.log
-  psql -X -q -d cuny_courses -f sessions.sql >> update_psql.log
+  psql -X -q -d cuny_courses -f sessions.sql >> update_psql.log 2>&1
   if [ $? -ne 0 ]
-    then echo -e '\nFAILED!'
-         exit
+    then update_failure 'ERROR: sessions failed'
+         exit 1
   fi
   echo done. | tee -a update_psql.log
 
   #echo CREATE TABLE pending_reviews...
   #echo CREATE TABLE event_types...
   echo -n "CREATE TABLE events... " | tee -a update_psql.log
-  psql -X -q -d cuny_courses -f reviews-events.sql >> update_psql.log
+  psql -X -q -d cuny_courses -f reviews-events.sql >> update_psql.log 2>&1
   if [ $? -ne 0 ]
-    then echo -e '\nFAILED!'
-         exit
+    then update_failure 'ERROR: reviews-events failed'
+         exit 1
   fi
   echo done. | tee -a update_psql.log
 
   if [[ $no_events -ne 1 ]]
   then
     echo -n "RESTORE previous events from $EVENTS_TABLE ... " | tee -a update_psql.log
-    psql -X -q -d cuny_courses -f $EVENTS_TABLE >> update_psql.log
+    psql -X -q -d cuny_courses -f $EVENTS_TABLE >> update_psql.log 2>&1
     if [ $? -ne 0 ]
-      then echo -e '\nFAILED!'
-           exit
+      then update_failure 'ERROR: restore events_table failed'
+           exit 1
     fi
     echo done. | tee -a update_psql.log
+
     echo ARCHIVE the events table.
     mv $EVENTS_TABLE ./event_dumps/
 
     echo -n "UPDATE review statuses... " | tee -a update.log
-    python3 update_review_statuses.py >> update.log
+    python3 update_review_statuses.py >> update.log 2>&1
     if [ $? -ne 0 ]
-      then echo -e '\nFAILED!'
-           exit
+      then update_failure 'ERROR: review_statuses failed'
+           exit 1
     fi
     echo done. | tee -a update.log
   fi
 
   # User roles and access
   echo -n "Re-build the roles and person_roles tables ..." | tee -a update_psql.log
-  psql -X -q -d cuny_courses -f roles.sql >> update_psql.log
+  psql -X -q -d cuny_courses -f roles.sql >> update_psql.log 2>&1
   echo done. | tee -a update_psql.log
 
   echo -n "(Re-)Grant select access to view_only ROLE ..." | tee -a update_psql.log
-  psql -X -q -d cuny_courses -f view_only_role.sql >> update_psql.log
+  psql -X -q -d cuny_courses -f view_only_role.sql >> update_psql.log 2>&1
   echo done. | tee -a update_psql.log
 
   # Exit update_db mode
@@ -419,7 +421,8 @@ function update_failure () {
   psql  access_control -c \
         "update access_control set start_time = NULL where event_type = 'update_db'"
 
-  echo UPDATE COMPLETED in `gdate -d @"$SECONDS" +'%-Mm %-Ss'` | tee -a update.log
+  echo UPDATE COMPLETED at `date +"%Y-%m-%d %T"` in `gdate -d @"$SECONDS" +'%-Mm %-Ss'` | \
+       tee -a update.log
 
 if [[ ! ( $no_programs == 1 || $no_programs == true ) ]]
 then
