WIP

diff --git a/update_db b/update_db
--- a/update_db
+++ b/update_db
@@ -118,6 +118,8 @@ function send_notice () {
       then no_archive=true
     elif [[ ( "$1" == "--no-programs" ) || ( "$1" == "-np" ) ]]
       then no_programs=true
+    elif [[ ( "$1" == "--ignore-new" ) || ( "$1" == "-in" ) ]]
+      then ignore_new=true
     else
       echo "Usage: $0 [-ne | --no-events] [-ns | --no-size-check] [-nd | --no-date-check]
        [-na | --no-archive] [-sd | --skip_download] [-np | --no_programs] [-i | --interactive]"
@@ -127,7 +129,10 @@ function send_notice () {
   done
 
   # Can't do downloads except from a cuny.edu host.
-  [[ ! ( `hostname` =~ cuny.edu ) ]] && skip_download=true
+  if [[ ! ( `hostname` =~ cuny.edu ) ]]
+  then echo "Cannot access Tumbleweed from `hostname`"
+       skip_download=true
+  fi
 
   # # Uncomment for debugging
   # for arg in no_events skip_download no_size_check no_date_check no_archive no_programs
@@ -139,7 +144,7 @@ function send_notice () {
   # done
 
   # Include path to update.log file so script can be invoked from any directory.
-  export update_log=`pwd`/$update_log
+  export update_log=`pwd`/update.log
   truncate -s0 $update_log
 
   echo BEGIN UPDATE at `date +"%Y-%m-%d %T"` | tee -a $update_log
@@ -167,7 +172,7 @@ function send_notice () {
   [[ $no_size_check ]] && args="$args -ss"
   [[ $no_date_check ]] && args="$args -sd"
   [[ $no_archive ]] && args="$args -sa"
-  [[ $skip_download ]] && args="$args --ignore_new"
+  [[ $ignore_new ]] && args="$args --ignore_new"
 
   ./check_queries.py $args >> $update_log 2>&1
   if [ $? -ne 0 ]
