Add app availability control to update_db.

diff --git a/update_db b/update_db
--- a/update_db
+++ b/update_db
@@ -1,14 +1,20 @@
 #! /usr/local/bin/bash
 
-# Run the sequence of sql and python scripts to create and initialize the cuny_courses database.
+# Run the sequence of sql and python scripts to re-create and update the cuny_courses database.
 
-# Summary of recommendations from http://petereisentraut.blogspot.com/2010/03/running-sql-scripts-with-psql.html
-# PGOPTIONS='--client-min-messages=warning' psql -X -q -a -1 -v ON_ERROR_STOP=1 --pset pager=off -d mydb -f dump.sql
+# Summary of recommendations from:
+#    http://petereisentraut.blogspot.com/2010/03/running-sql-scripts-with-psql.html
+#
+# PGOPTIONS='--client-min-messages=warning' psql -X -q -a -1 -v ON_ERROR_STOP=1 --pset pager=off \
+#            -d mydb -f dump.sql
+#
 #   --client-min-messages=warning to suppress NOTICE messages
 #   -X suppress reading .psqlrc (where I set timing)
 #   -f rather than < to get line numbers when a command fails
 #   -q to suppress CREATE TABLE, etc messages
-#   Others pertain more to restoring dump files, where a single transaction would make sense, and are not used here
+#   Others pertain more to restoring dump files, where a single transaction would make sense, and
+#   are not used here.
+
 (
   export PGOPTIONS='--client-min-messages=warning'
 
@@ -38,6 +44,25 @@
          exit 1
   fi
 
+  # Enter update_db mode if local server is running
+  echo -n "RESTART Postgres ..." | tee -a init.log
+  brew services restart postgresql
+  if [[ $? -ne 0 ]]
+    then echo -e '\nFAILED!'
+         exit
+  fi
+  #  Wait for postgres to restart
+  sleep 2
+
+  echo -n "CHECK transfer app... " | tee -a init.log
+  ps -fe | ack '[g]unicorn|main.py' > /dev/null
+  if [[ $? -eq 0 ]]
+  then curl --silent http://localhost:5000/_status/start_update > /dev/null
+       sleep 1
+       echo " update_db mode set" | tee -a init.log
+  else echo " app not running" | tee -a init.log
+  fi
+
   # Save events table unless suppressed by command line
   if [ $do_events -eq 1 ]
   then
@@ -46,7 +71,7 @@
     touch events-dump.sql
     echo -n SAVE EVENTS TABLE ...
     # events-dump.sql won’t be changed if "no matching tables found"
-    pg_dump --data-only --table=events -f events-dump_`date -I`.sql cuny_courses
+    pg_dump --data-only --table=events -f events-dump_`date +'%F_%H:%M'`.sql cuny_courses
     # Convert old-style group numbers (ints) to floats
     #   This can go away once all old-style reviews have been converted.
     # python3 fix_events_dump.py < events-dump_`date -I`.sql > t.sql
@@ -54,9 +79,19 @@
     echo done.
   fi
 
-  echo -n "DROP/CREATE cuny_courses... " | tee init_psql.log
+  echo -n "DROP cuny_courses... " | tee init_psql.log
   dropdb cuny_courses >> init_psql.log
+  if [[ $? -ne 0 ]]
+    then  echo -e '\nFAILED!'
+          curl --silent http://localhost:5000/_status/end_update > /dev/null
+          exit
+  fi
+  echo -n "CREATE cuny_courses... " | tee -a init_psql.log
   createdb cuny_courses >> init_psql.log
+  if [[ $? -ne 0 ]]
+    then echo -e '\nFAILED!'
+         exit
+  fi
   echo done. | tee -a init_psql.log
 
   echo -n "CREATE FUNCTION numeric_part... " | tee -a init_psql.log
@@ -245,5 +280,13 @@
     fi
     echo done. | tee -a init.log
   fi
-  echo INITIALIZATION COMPLETED in `date -d @"$SECONDS" +'%-Mm %-Ss'` | tee -a init.log
+
+  # Exit update_db mode if local server is running
+  ps -fe | ack '[g]unicorn|main.py' > /dev/null
+  if [[ $? == 0 ]]
+  then curl --silent http://localhost:5000/_status/end_update > /dev/null
+  fi
+
+
+  echo UPDATE COMPLETED in `date -d @"$SECONDS" +'%-Mm %-Ss'` | tee -a init.log
 )
